import { test, expect } from '@playwright/test'

const screen = page => page.locator('.xterm-rows')
const panel = page => page.getByRole('region', { name: 'linux terminal' })
const introHint = 'prefer clicking around? switch to file explorer in the top left.'

async function expectIntroHint(page) {
  const transcript = (await screen(page).innerText()).replace(/\s/g, '')
  const hint = introHint.replace(/\s/g, '')
  expect(transcript).toContain(hint)
  expect(transcript.indexOf(hint)).toBeLessThan(transcript.indexOf('catabout.txt'))
}

async function ready(page) {
  await expect(panel(page)).toHaveAttribute('data-booting', 'false')
}

async function command(page, text) {
  await ready(page)
  await page.getByRole('textbox', { name: 'terminal command' }).focus()
  await page.keyboard.press('Control+u')
  await page.keyboard.type(text)
  await page.keyboard.press('Enter')
}

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
})

test('terminal uses a full-screen character grid and compact shell output', async ({ page }, info) => {
  await ready(page)
  await expect(screen(page)).toContainText('parth@portfolio:~$')
  await expect(screen(page)).toContainText('projects')
  await expect(screen(page)).not.toContainText('permissions')
  await expect(screen(page)).not.toContainText('directory:')
  await expect(panel(page).locator('h1, table, .terminal-input-row')).toHaveCount(0)
  const bounds = await page.locator('.desktop').boundingBox()
  expect(bounds).toMatchObject({ x: 0, y: 0, width: page.viewportSize().width, height: page.viewportSize().height })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)).toBe(true)
  await page.screenshot({ path: info.outputPath('terminal.png'), fullPage: true })
  await page.getByRole('button', { name: 'file explorer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'home', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'grid view' })).toHaveAttribute('aria-pressed', 'true')
  const files = page.locator('.explorer-files')
  await expect(files.locator('img')).toHaveCount(8)
  await expect.poll(() => files.locator('img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))).toBe(true)
  expect(await page.locator('.explorer-panel').evaluate(el => getComputedStyle(el).fontFamily)).toContain('Ubuntu')
  await expect(page.locator('.sidebar-bottom, .explorer-toolbar')).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('explorer.png'), fullPage: true })
})

test('commands navigate, complete, read files, recall history, and clear', async ({ page }) => {
  await ready(page)
  await page.getByRole('textbox', { name: 'terminal command' }).focus()
  await page.keyboard.type('cd proj')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('cd projects/')
  await page.keyboard.press('Enter')
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth/projects')
  await command(page, 'cd order-book')
  await command(page, 'cat readme.md')
  await expect(screen(page)).toContainText('c++20 order book')
  await page.keyboard.press('ArrowUp')
  await expect(screen(page)).toContainText('cat readme.md')
  await page.keyboard.press('ArrowDown')
  await command(page, 'clear')
  await expect(screen(page)).not.toContainText('c++20 order book')
  await expect(screen(page)).toContainText('parth@portfolio:~/projects/order-book$')
  await command(page, 'tree ~')
  await expect(screen(page)).toContainText('photography.url')
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth/projects/order-book')
})

test('input supports editing and Shift+Tab leaves the terminal', async ({ page }) => {
  await ready(page)
  const input = page.getByRole('textbox', { name: 'terminal command' })
  await input.focus()
  await page.keyboard.type('c projects')
  await page.keyboard.press('Home')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.type('d')
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth/projects')
  await page.keyboard.press('Shift+Tab')
  await expect(input).not.toBeFocused()
})

test('writing shortcut and filename completion open the essay link', async ({ page }) => {
  await command(page, 'clear')
  await command(page, 'ls writing')
  await expect(screen(page)).toContainText('road_design.url')
  await command(page, 'cat road_design.url')
  await expect(screen(page)).toContainText('cat writing/road_design.url')
  await command(page, 'writing')
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth/writing')
  await page.keyboard.type('cat roa')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('cat road_design.url')
  await page.keyboard.press('Enter')
  await expect(screen(page)).toContainText('/public_remediation')
})

test('easter eggs print in the terminal and leave navigation working', async ({ page }) => {
  await command(page, 'cd projects')
  await command(page, 'clear')
  await command(page, 'sudo rm -rf ~')
  await expect(screen(page)).toContainText('relationship with this website')
  await command(page, 'cowsay "hello there"')
  await expect(screen(page)).toContainText('hello there')
  await command(page, 'sl')
  await expect(screen(page)).toContainText('try ls')
  await command(page, 'vim readme.md')
  await expect(screen(page)).toContainText(':q')
  await command(page, ':q')
  await command(page, 'exit')
  await expect(screen(page)).toContainText('you live here now')
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth/projects')
  await command(page, 'ls')
  await expect(screen(page)).toContainText('order-book')
  await expect(screen(page)).not.toContainText('command not found')
})

test('wrapped commands can be edited without damaging prior output', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 650 })
  await command(page, 'clear')
  await command(page, 'pwd')
  const input = page.getByRole('textbox', { name: 'terminal command' })
  await input.focus()
  await page.keyboard.type('cat /home/parth/projects/order-book/readme.mdX')
  await page.keyboard.press('Backspace')
  await page.keyboard.press('Enter')
  await expect(screen(page)).toContainText('c++20 order book')
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth')
  await page.setViewportSize({ width: 844, height: 390 })
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('opening a file shows a dialog and Escape returns focus to the file', async ({ page }) => {
  await page.getByRole('button', { name: 'file explorer', exact: true }).click()
  const file = page.getByRole('button', { name: /^about.txt text document/ })
  await file.click()
  const preview = page.getByRole('dialog', { name: 'preview of about.txt' })
  await expect(preview).toBeInViewport()
  await page.keyboard.press('Escape')
  await expect(preview).not.toBeVisible()
  await expect(file).toBeFocused()
  if (page.viewportSize().width < 640) {
    await page.getByRole('button', { name: 'toggle folder sidebar' }).click()
    await page.getByRole('button', { name: 'open about.txt', exact: true }).click()
    await expect(preview).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(preview).not.toBeVisible()
    await expect(page.locator(':focus')).toBeVisible()
    expect(await page.locator(':focus').evaluate(el => el.tagName)).toBe('BUTTON')
  }
})

test('switching views preserves folder and output; Explorer history works', async ({ page }) => {
  await command(page, 'cd research')
  await command(page, 'ls')
  await command(page, 'explorer')
  await expect(page.getByRole('heading', { name: 'research', exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^uav-suspension file folder/ }).click()
  await page.getByRole('button', { name: 'back', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'research', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'forward', exact: true }).click()
  await page.getByRole('button', { name: 'terminal', exact: true }).click()
  await expect(screen(page)).toContainText('circumstellar-dust')
  await command(page, 'pwd')
  await expect(screen(page)).toContainText('/home/parth/research/uav-suspension')
})

test('Explorer search, file previews, grid, and links work', async ({ page }, info) => {
  await page.getByRole('button', { name: 'file explorer', exact: true }).click()
  await page.getByRole('button', { name: 'search files', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'search files', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'search files', exact: true }).click()
  await page.getByRole('textbox', { name: 'search current folder' }).fill('nonesuch')
  await expect(page.getByText('no files match', { exact: false })).toBeVisible()
  await page.getByRole('textbox', { name: 'search current folder' }).fill('contact')
  await page.getByRole('button', { name: /^contact.txt text document/ }).click()
  await expect(page.getByRole('dialog', { name: 'preview of contact.txt' })).toBeInViewport()
  await expect(page.getByRole('dialog', { name: 'preview of contact.txt' }).getByRole('link', { name: /mailto/ })).toHaveAttribute('href', 'mailto:pmhaske@umd.edu')
  await page.getByRole('button', { name: 'close preview' }).click()
  await page.getByRole('textbox', { name: 'search current folder' }).fill('')
  await page.getByRole('button', { name: 'list view' }).click()
  await expect(page.getByRole('button', { name: 'list view' })).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({ path: info.outputPath('list.png'), fullPage: true })
  await page.getByRole('button', { name: 'grid view' }).click()
  await expect(page.getByRole('button', { name: 'grid view' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: /^resume.pdf pdf document/ }).click()
  await expect(page.getByRole('link', { name: 'open résumé', exact: true })).toHaveAttribute('href', '/resume.pdf')
  await page.screenshot({ path: info.outputPath('preview.png'), fullPage: true })
})

test('ls is names-only, ls -l has Unix metadata, and files remain safe', async ({ page }) => {
  await command(page, 'clear')
  await command(page, 'ls')
  await expect(screen(page)).toContainText('about.txt')
  await expect(screen(page)).not.toContainText('drwx')
  await expect(screen(page)).not.toContainText('things i have built')
  await command(page, 'ls -l')
  await expect(screen(page)).toContainText('drwxr-xr-x')
  await command(page, 'rm -rf projects')
  await expect(screen(page)).toContainText('nothing was deleted.')
  await command(page, 'cd missing')
  await expect(screen(page)).toContainText('cannot find: missing')
  await command(page, 'cat about.txt')
  await expect(screen(page)).toContainText('class of 2028')
})

test('existing essay and static assets remain reachable', async ({ page, request }) => {
  for (const path of ['/resume.pdf', '/scavenger-hunt/', '/goose-chase/']) {
    expect((await request.get(path)).status()).toBe(200)
  }
  await page.goto('/public_remediation')
  await expect(page.getByRole('navigation', { name: 'Remediation navigation' })).toBeVisible()
  await page.getByRole('link', { name: 'Parth Mhaske', exact: true }).click()
  await expect(page.getByRole('button', { name: 'terminal', exact: true })).toBeVisible()
  await expect(page).toHaveTitle('parth mhaske')
})

test('startup types into the same buffer and does not replay', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.clock.install()
  await page.reload()
  await expect(panel(page)).toHaveAttribute('data-booting', 'true')
  await expect(screen(page)).toContainText('prefer clicking around?')
  const first = await screen(page).innerText()
  await page.clock.runFor(200)
  expect((await screen(page).innerText()).length).toBeGreaterThan(first.length)
  await page.clock.runFor(4000)
  await ready(page)
  await expect(screen(page)).toContainText('cat about.txt')
  await expectIntroHint(page)
  await page.getByRole('button', { name: 'file explorer', exact: true }).click()
  await page.getByRole('button', { name: 'terminal', exact: true }).click()
  await ready(page)
  await expect(page.getByRole('button', { name: /skip intro/ })).toHaveCount(0)
  await expectIntroHint(page)
  expect((await screen(page).innerText()).match(/prefer clicking around\?/g)).toHaveLength(1)
})

test('startup skips with a button or Escape and respects reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.clock.install()
  await page.reload()
  await page.getByRole('button', { name: /skip intro/ }).click()
  await ready(page)
  await expectIntroHint(page)
  await page.reload()
  await page.keyboard.press('Escape')
  await ready(page)
  await expectIntroHint(page)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.reload()
  await ready(page)
  await expectIntroHint(page)
  await expect(page.getByRole('button', { name: /skip intro/ })).toHaveCount(0)
})
