import { test, expect } from '@playwright/test'

const screen = page => page.locator('.xterm-rows')
const input = page => page.getByRole('textbox', { name: 'terminal command' })
const ready = page => expect(page.getByRole('region', { name: 'linux terminal' })).toHaveAttribute('data-booting', 'false')

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await ready(page)
  await input(page).focus()
})

test('rapid typing has no per-key backlog at four times CPU slowdown', async ({ page }, info) => {
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Emulation.setCPUThrottlingRate', { rate: 4 })
  const command = 'latency_probe_' + 'x'.repeat(220)
  const started = Date.now()
  await page.keyboard.type(command)
  const typingMs = Date.now() - started
  await page.keyboard.press('Enter')
  const submitted = Date.now()
  await expect(screen(page)).toContainText('command not found: latency_probe_', { timeout: 1500 })
  const drainMs = Date.now() - submitted
  console.log(`${info.project.name} 4x CPU: ${typingMs}ms typing, ${drainMs}ms drain`)
  expect(drainMs).toBeLessThan(1500)
})

test('bulk text input and rapid commands after clear are preserved', async ({ page }) => {
  await page.keyboard.insertText('clear')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('cd projects')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('pwd')
  await page.keyboard.press('Enter')
  await expect(screen(page)).toContainText('/home/parth/projects')
  await expect(screen(page)).not.toContainText('file explorer is in the top left.')
  await page.keyboard.insertText('cat /home/parth/about.txt')
  await page.keyboard.press('Enter')
  await expect(screen(page)).toContainText('class of 2028')
})

test('paste stays inert and wrapped Unicode edits do not lose the command', async ({ page }) => {
  await input(page).evaluate(element => {
    const clipboardData = new DataTransfer()
    clipboardData.setData('text/plain', 'cd projects\nrm -rf ~')
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData, bubbles: true, cancelable: true }))
  })
  await expect(screen(page)).toContainText('cd projects rm -rf ~')
  await expect(screen(page)).not.toContainText('nothing was deleted')
  await page.keyboard.press('Control+c')
  await page.keyboard.insertText('cat /home/parth/projects/order-book/readme.md🦉界')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Backspace')
  await page.keyboard.press('Delete')
  await page.keyboard.press('Enter')
  await expect(screen(page)).toContainText('c++')
  await expect(screen(page)).not.toContainText('cannot find:')
})

test('cold-load input before startup settles opens the requested reader at four times CPU slowdown', async ({ page }) => {
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Emulation.setCPUThrottlingRate', { rate: 4 })
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.addInitScript(() => {
    new MutationObserver((_, observer) => {
      const textarea = document.querySelector('textarea[aria-label="terminal command"]')
      if (!textarea) return
      observer.disconnect()
      window.startupInputState = document.querySelector('[data-booting]')?.getAttribute('data-booting')
      textarea.focus()
      textarea.dispatchEvent(new InputEvent('beforeinput', { inputType: 'insertText', data: 'view uav', bubbles: true, cancelable: true }))
      textarea.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', code: 'Enter', keyCode: 13, which: 13, bubbles: true, cancelable: true }))
    }).observe(document, { subtree: true, childList: true, attributes: true })
  })
  await page.reload()
  expect(await page.evaluate(() => window.startupInputState)).toBe('true')
  await ready(page)
  await expect(screen(page)).toContainText('view uav')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog')).toBeFocused()
})

test('Tab completes commands, paths and quoted command chains without leaving the terminal', async ({ page }) => {
  await page.keyboard.type('c')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('parth@portfolio:~$ cd')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('parth@portfolio:~$ cat')
  await page.keyboard.press('Control+u')
  await page.keyboard.type('over')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('parth@portfolio:~$ overview')
  await page.keyboard.press('Control+u')
  await page.keyboard.type('cd pro')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('parth@portfolio:~$ cd projects/')
  await page.keyboard.press('Control+u')
  await page.keyboard.type('cowsay "a; b"; cd projects && cd or')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('cd projects && cd order-book/')
  await expect(input(page)).toBeFocused()
  await page.keyboard.press('Enter')
  await page.keyboard.type('cat re')
  await page.keyboard.press('Tab')
  await expect(screen(page)).toContainText('cat readme.md')
})
